### ISSUE TITLE
Requirement: every repository should get a unique stable URL

### ISSUE THREAD

**Issue by firaswehbe** [NUBIC/disburser#40]
So repositories can be linked from the individual public website of the entity that manages it (eg brain, Prostate SPORE ...)

**Comment by mgurley** [comment]
Do you mean like a slug URL?

Instead of:
https://disburser-staging.cancer.northwestern.edu/repositories/7

Something like:
https://disburser-staging.cancer.northwestern.edu/repositories/breastrepository
@firaswehbe @nutodd

**Comment by firaswehbe** [comment]
Doesn't matter if it's a slug URL or not as long as individual repositories are exposed via unique URL that does not change so as not to break links from individual groups who support / advertise them elsewhere.

**Comment by mgurley** [comment]
The system has a stable URL for every repository.
