### ISSUE TITLE
Remove the IRB number field for disbursement requests with custom request form.

### ISSUE THREAD

**Issue by mgurley** [NUBIC/disburser#73]
Based on feedback from Katy and Dr. Horbinski meeting on 2/24/2016

**Comment by mgurley** [comment]
At meeting at 2/27 Firas decided we should keep this item.  Even if it might duplicate an item an a custom request form.

**Comment by firaswehbe** [comment]
Rationale for keeping: one of the purposes of the system is to measure the research volume utilizing tissue repositories. STU numbers are crucial for these analytics including ascertaining investigator home departments and scientific programs
